name: generate-docs

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: langroodi/doxygenize@v1.3
        with:
          doxygenconf: './Doxyfile'
          htmloutput: './Documentation/html'
          ghpagesbranch: 'gh-pages'
          ghpagesdir: './'
